### ISSUE TITLE
Technical Debt Branch

### ISSUE THREAD

**Issue by DillonAd** [NickCraver/BadIdeas#2]
Every decent project has technical debt! I propose a :rage: branch for easily foreseen technical debt that should have been avoided in the first place. 

Alternate branch name ideas:
 - 💩 
 - ⁉️ 
 - 🆘

**Comment by mohamedebrahim96** [comment]
yes, you are right
make a pull request and update the readme file.

**Comment by SteveEdson** [comment]
Kind of reminds me of this: https://csswizardry.com/2013/04/shame-css/
